apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectassignment
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: 8192027760/project:14456433837
        ports:
        - containerPort: 5000
